### ISSUE TITLE
latest commit fails to build on ppc64le architecture (Fedora rawhide-devel)

### ISSUE THREAD

**Issue by rosset** [vitalif/grive2#153]
https://kojipkgs.fedoraproject.org//work/tasks/3701/20833701/build.log
+ export LDFLAGS
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON .
RPM build errors:
/usr/bin/cmake: error while loading shared libraries: /lib64/librt.so.1: expected localentry:0 `pthread_attr_setdetachstate'
error: Bad exit status from /var/tmp/rpm-tmp.xiTRu0 (%build)
    Bad exit status from /var/tmp/rpm-tmp.xiTRu0 (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.5/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target ppc64le --nodeps /builddir/build/SPECS/grive2.spec

**Comment by vitalif** [comment]
Hi. O_o good. But it seems unrelated to grive code.
Maybe this will help?
https://bugzilla.redhat.com/show_bug.cgi?id=1475636
https://bugzilla.redhat.com/show_bug.cgi?id=1479031

**Comment by rosset** [comment]
yeah, I'll take a look in this issue soon, thanks.
