### ISSUE TITLE
Segfault in ArchLinux (gr::State::Update method)

### ISSUE THREAD

**Issue by mbellgb** [vitalif/grive2#156]
Hello, when running `grive --dry-run` I get a segmentation fault as shown:

```
▲ ~ grive -p ~/google --dry-run
Reading local directories
Reading remote server file list
[1]    6449 segmentation fault (core dumped)  grive -p ~/google --dry-run
```

Coredump info

```
▲ ~ coredumpctl info /usr/bin/grive
           PID: 6449 (grive)
           UID: 1000 (mbell)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Tue 2017-09-05 10:46:23 BST (15s ago)
  Command Line: grive -p /home/mbell/google --dry-run
    Executable: /usr/bin/grive
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (mbell)
       Boot ID: e089999fc21f4a8d88c3e8404cbb30b8
    Machine ID: 05d4564348034d84a1079cf08d045912
      Hostname: moorgate
       Storage: /var/lib/systemd/coredump/core.grive.1000.e089999fc21f4a8d88c3e8404cbb30b8.6449.1504604783000000.lz4
       Message: Process 6449 (grive) of user 1000 dumped core.
                
                Stack trace of thread 6449:
                #0  0x000055de111cc25d n/a (grive)
                #1  0x000055de1116e6b8 _ZN2gr5State6UpdateERKNS_5EntryE (grive)
                #2  0x000055de1116f3f8 _ZN2gr5State12ResolveEntryEv (grive)
                #3  0x000055de1116b269 _ZN2gr5Drive13DetectChangesEv (grive)
                #4  0x000055de1115d5c3 _Z4MainiPPc (grive)
                #5  0x000055de1115b4dd main (grive)
                #6  0x00007fa6553894ca __libc_start_main (libc.so.6)
                #7  0x000055de1115c37a _start (grive)
```

GDB analysis:

```
(gdb) bt
#0  0x000055de111cc25d in ?? ()
#1  0x000055de1116e6b8 in gr::State::Update(gr::Entry const&) ()
#2  0x000055de1116f3f8 in gr::State::ResolveEntry() ()
#3  0x000055de1116b269 in gr::Drive::DetectChanges() ()
#4  0x000055de1115d5c3 in Main(int, char**) ()
#5  0x000055de1115b4dd in main ()
```

Grive seems to be working fine when running on a new directory, so either there's a problem with that specific directory, or there's a problem with the dry run option.

```
▲ ~ pacman -Qi binutils 
Name            : binutils
Version         : 2.28.0-4
```

Thanks!

**Comment by vitalif** [comment]
Hi. Can you make a debug build and rerun your case? It should print line numbers.
